global_frame: odom
rolling_window: true
width: 3.0
height: 3.0

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_l,                 type: "costmap_2d::InflationLayer"}
